apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.service | lower | quote }}
  labels:
    app.kubernetes.io/name: {{ .Values.service | lower | quote }}
    app.kubernetes.io/part-of: {{ .Values.system | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec: 
  hosts:
    - {{ (print .Values.service "." .Release.Namespace ".svc.cluster.local") | quote }}
  http:
    - route:
      - destination:
          host: {{ (print .Values.service "." .Release.Namespace ".svc.cluster.local") | quote }}
          subset: {{ (print "v" .Values.version) | quote }}
{{- if .Values.retries }}
      retries:
{{ toYaml .Values.retries | indent 8 }}
      timeout: {{ required "You must specify an overall timeout to use retries" .Values.overallTimeout}}
{{- else if .Values.overallTimeout }}
      timeout: {{ .Values.overallTimeout }}
{{- end }}
