version: '3.7'

services:
  web:
    build:
      context: .
    image: pp_fastapi:0.1
    ports:
      - 8000:8000
    volumes:
      # Persist sqlite & reload app on code changes
      - ./:/usr/src/app
    command: "hypercorn --bind 0.0.0.0:8000 --reload cities.main:app"