AWSTemplateFormatVersion: 2010-09-09

Description: Template to create an EC2 instance and enable SSH

Parameters:
  KeyName:
    Description: Name of SSH KeyPair
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Provide the name of an existing SSH key pair

Resources:
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 51.38.114.48/32
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0a5e707736615003c # ami for eu-west-1
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - sg-811353fc
        - !Ref InstanceSecurityGroup
      Tags:
        - Key: Name
          Value: TestCloudFormation

Outputs:
  InstanceID:
    Description: The Instance ID
    Value: !Ref MyEC2Instance
